---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
spec:
  encryptedData:
    config.production.json: AgC1eaGp5r4Gq6q49VoVBDMavcteOm8DGpol7aAyiY9RNVS6t6cPrpUvrJ7XGH81jcgw+qTXXXpKuhdEQSO8DkSYZlZdEUg5e++JGsNWerpAXoZwYQyYX46Ej7z38eElXWHVi1PNat26L8c6QZBAV/L/akwRDchA/D4UcEUs/AmIKrPfJavt4l1PU4NtTKtc+S7BDj+7DL4+F8KqbZqh6xTs0yZoquklcFHAeP7FnyWDN1dYjHLyu/bKbArW27y+fm1XkOQmUS9pIXrkim//ajfgqVFT/hYN6yFGuqKfh4bRv5VwFCT0LFCFRXvNlpy3LEkTjGK5/AbVodO3nk07BvO1p4oJrqHXr9UiTfxzgNdXPLIjGdtb/r/oNZlpbxprfFMudreYg3a1tCNmKhwalHzCZ5iz0cQPw1sP07mwQkwPTkELP8JzFR4Doyj1UFXNG7BzL+Nqk0+mTIUawRsQCnRttckNP2kiX/i3MDNUOCTNhcADNN1WjXYOv6yC1ODkMAxj8u/Nfq6KGJENXihzsjyd/UX/BH20Nt/Od0fhi4a3DL2solSdJt9tIvidngIujNwnONni5r6QgFntyAGNb5DJ60v3ZETo7imHHQ5ciEUwRWW5tEF6qqpA4xIwc1AeQoFphmL4t3Fr+TzwR0VLVP6czEHTMU/bVPU2FvPl5mXQCmpk7+NgMS5vgLILU8imTTUK0EReMMEBGPkZvcyLCyjG8aRK9ZROZSDMr24uOhOCT3xpTTeuj5zsDesiBsgZMrvY14lwNF6tzKBCM5eF6eC6iaW+Cd14HmvvfZAT/5SVO5QPttQXbDatslYMmY2TxajT2mGEPmykqf4Z1D5GSyiyU0RNQBAsKkNcYP9xTyc+suf1GlefGig8DyrH8qrUUerOroKabK4gSalnhWRaFmWzI90wJcfoqvwl4FKO/Pt1QAEk4b00ttxbtF54xK+PtR1MRjk1/hz91osVSqShpDl8UBvqEzXnITYVuYszwXeRaG+Ym/yGQpXxs5FZI65lmsfwCdW8pxapmWlBCD/iieF25Lq+lKmgbZ1xTZP5ZtlIRAiJ0ZKzjciqYmTUyA08xCgY8ah/UwBCv0kmQHIbBGXARe6L7ry3SAoiBSRPA/dQmHDg5lIYQdU6xL65qV7peCTHhORLByiqV7qLq+c+sPv1pxIfucYuxCMzs5jTB+IvzQF8sup4k5Xheb4r2v6byRNJhDebCQRecFfZhQkGceZof++vpoLOb6eWW6UTcVz24zgOnqAYqSrN41Uh6wnQY+XZ8JLAZYqu4p0WfPyOWK5t68zVO7FBDYQ93qJgrFaS6WIeMV5kV5cA4ZDfdg5B9OHx/hUHQstD/TBDyvV3LTJ0fvhdD9iuNN9L8S+RL3LRkqbspOwxBrS46bdxDZyHjRK3P2wPqgzbSEA/xCfhBLujPI9yC0ZO4eBqykmMvhEEYrZD9h5dVCguQooGboQT23QLNb00yNt1OLxm4dewsEz9jpA8mjGnRB2AIiCRxqMFTq/EWEzwqG1AjiZwEwZWUaePP1/m7UNMUDxsqwePsMGJv0RhO6hvoyiHQkXSC3X+DvexAfLWTIDS0qcYbhPVe4iwuMyG4i5EPkXLlKSjQl7hcKNWfuarJJhxzYC8/GONoYkupv0lv4Y+FvhudHylc/byNdWxen7+T43iEYJPmO4GZ8CrnOxRuS/dzyxN5knmRPqGkTS2UN2/ajC/4xP4TscHVzFKFiGjqCe0mLYFlM2CXvq/0kgO88YGEQzh/dXIq9/cKYr39K9EpKNJlnqCUOxgY1xFlXgsBXQROlMqvPDZxJS6IU0g8G3a86vEtKIT9vSqpzSZpu7Fz4BhBJlte1XTcclHX43RBkEs6P4b7dB7a+0pBJ9mTOuD
  template:
    metadata:
      labels:
        app: ghost-on-kubernetes
        app.kubernetes.io/component: ghost-config
        app.kubernetes.io/instance: ghost-on-kubernetes
        app.kubernetes.io/name: ghost-config-prod
        app.kubernetes.io/part-of: ghost-on-kubernetes
        app.kubernetes.io/version: "5.92"
      name: ghost-config-prod
      namespace: ghost-on-kubernetes
    type: Opaque
