apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ghost-route
  namespace: ghost-on-kubernetes
spec:
  parentRefs:
  - name: homelab-gateway
    namespace: gateway
  hostnames:
  - "blog-admin.thorntoncloud.com"
  rules:
  - backendRefs:
    - name: ghost-on-kubernetes-service
      port: 2368