apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared-tunnel
  labels:
    app: cloudflared
    app.kubernetes.io/name: ghost-on-kubernetes
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: ghost-on-kubernetes
    shared-gateway-access: "true"
