---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    token: AgBbwAAxWLrQF6rl3c3ANJcLKCnICAQ30siNkHFU/GKeXtmt1cN8R6+pRtoOTb+yv4S6svlOb+tPStIyZorKDaIdnfDyVEQzvtvlHXslw7BgDUa1lQkxLXyATcS9avQvuexPa2L7V0eRzflIqF65to0TC4ZhliibuZOnFKdlydBnwLN4aJq+zvXF/9LDBVbhg2QQSkqqIL+5ONLyRBk49mqL8eRAe5sfadeJyaKaJvIB/n2LpNR7H30QZkwFdBJKaPjZHgdG9vqb7QkMm2Au/AZSHOYPWYML8ivrzDJtVM9Wx/jr4CfEajQknXiVz57hLec2JBUHOUutpB0SyX4uazGyQN9eyLwfV+zHiM1AL6XEpK32MHccV1zlIMLWLWHgqGtjetOVCHIuwP2XvJoNc3NrodOcuPAQ8n2vJkqcqFNhFJPUu1KS9CNLNgj8XQ/7NeErWGeiLIkRMntKcJVcksLq87RIY4zoAsFORCWdgccXad55Z0eYBRLfS/+YGHRsei/YHVUG4omu9JLI6G3sFENgRMHua7MHHOyMVFfRLj/d8d5wdfL1eNhj7VkUvLWYCmPllElgVufvK8tw4xnvcCFe3KaIuMBHE1nopvPSMBT3Tp1x+35Oy2MBlGLMcwHnYGWnP7cLPw51dhVvNwj609aoo83BgbuBlOdntryRfJR3iTDCAfAVPRzmue1JSVg4yrV4YBMZ/RzM7/348LwCJiVzz+kmO4tX74wS+XDjcBxdROo2Luyx7dcoLw3PjJM4WWbS1FrrUQVv9io4GosNlOzM5Hd2+KWOuMXnAnp34LVY4Z3CS7wdUfNu5EVJJuIeJXWG3ZHKMNCXMi8K9kbW6Y0H/bi3UeWC1LVuaEud7q3kq3fIepg5ohotkMdCaR0C26yH1IB3DIY4mXvLu4wMRQLM01OIR9pKWtGZOGuyB7TtyxS5xKcmks+E
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared-tunnel
