apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared-tunnel
stringData:
    token: ENC[AES256_GCM,data:Od+EoRNkBN7iTdCHUSktuLXI5TwjhiP72gbVftC4dwGelQd/gDDJc8HC3NLEBpFzTLfyP6pXpqljl55bpdtm3wrD2ZCqLGwbsj8fse/iMiDDVglzydsSye7b863N/OJTsU7AyfYuBD0a0fj6WgnIYVuoSqyOt4Eu15LV83Ng8C4fOjYlQ4ijy0dqJF+VIxidZkWm3CoWHSTNM2agqd0mKYfD077dc8KJuu0/zgkuwpPUvMxNXskF9A==,iv:uvc6utjI2V/bbJq++zALZ6Kz8NUjCbvp9fe1EKIGqmE=,tag:cp7dpUhm3XwtRplVgCWEGw==,type:str]
sops:
    age:
        - recipient: age193xe078xg59flywzx9wrjlnsd06f5akn3mn6uhma8nrea62hdqkqs5eesu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcTFXL0w0elF0NEhiN3g0
            WXJqNUxQb3Ztc2VuNnBXVk9wTFV1SW1MZEQ0CmhuMmdaM2ZVVTBOM0E0T1JqTDNT
            Z2ZmTGNLUnQ5WkFpR0JuY1BEZVpmaWcKLS0tIGdHanlFMXIvbFJyWnRqT1Jxcnl6
            N1QzUlhJZTVlcWUwc2VBRnNWNjZXVTAKYdo1LZYXgroJD6rC9lMkCVqfuPTRhIGK
            I78/PorAw0rN0B9iqDGO7OkgRtIrQyVqYhSVZ+bexM4LelVWPWQBiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T19:20:10Z"
    mac: ENC[AES256_GCM,data:3zzrPXbvkt1ukPYEUm5e1aJO3FZ28lMIZx8d7sxaYssxk+k3wjoRwO4hOi4XwU89Gsl1P5PEfpBIKMiJC6/TMFLsvOCfc5P6SDBuNeNAjNIwWhj3/xOpafLlmkKxFVm2YVnms6favUExbodjtxJ1G0y3xW0jmefmWqKdUX/qinM=,iv:01wIIaUAGlUJfeq788mzyVEAahSdlNUKzx2HJF2LiSE=,tag:E2KLvbLmZj3xF/o8KOnlQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
